In [12]:
import pandas as pd
import numpy as np
import math
import glob
import os

## Position Performance Through the Years Cleaning

Creating a for loop to run through all of the files in the data folder, taking only rankings 1-8 (starting lineup), combining them, then adding a new column for the year to making plotting easier down the road.

In [60]:
files = glob.glob('data/*csv')
dfs = []
for file in files:
    df = pd.read_csv(file)
    df['Year'] = file
    df = df[(df['Rk'] < 9)]
    dfs.append(df)
    df['Year'] = df['Year'].str.split('_').str[0]

df = pd.concat(dfs, ignore_index=True)
df['Year'] = df['Year'].str.split('/', n=1).str[-1]
df.to_csv('data/cleaned/batting_order_history.csv', index=False)
df

,Rk,Pos,Name,Age,G,PA,AB,R,H,2B,...,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,Year
0,1.0,C,Mike Piazza,37.0,126.0,439.0,399.0,39.0,113.0,19.0,...,0.501,0.843,122.0,200.0,13.0,3.0,0.0,3.0,2.0,2006
1,2.0,1B,Adrian Gonzalez*,24.0,156.0,631.0,570.0,83.0,173.0,38.0,...,0.500,0.862,127.0,285.0,24.0,3.0,1.0,5.0,9.0,2006
2,3.0,2B,Josh Barfield,23.0,150.0,578.0,539.0,72.0,151.0,32.0,...,0.423,0.741,96.0,228.0,8.0,2.0,2.0,5.0,7.0,2006
3,4.0,SS,Khalil Greene,26.0,121.0,460.0,412.0,56.0,101.0,26.0,...,0.427,0.747,97.0,176.0,15.0,7.0,0.0,2.0,0.0,2006
4,5.0,3B,Vinny Castilla,38.0,72.0,269.0,254.0,24.0,59.0,10.0,...,0.319,0.579,54.0,81.0,5.0,2.0,0.0,4.0,0.0,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,4.0,SS,Garry Templeton#,27.0,126.0,490.0,460.0,39.0,121.0,20.0,...,0.335,0.629,77.0,154.0,16.0,0.0,7.0,2.0,7.0,1983
412,5.0,3B,Luis Salazar,27.0,134.0,510.0,481.0,52.0,124.0,16.0,...,0.387,0.672,87.0,186.0,4.0,2.0,8.0,2.0,8.0,1983
413,6.0,LF,Bobby Brown#,29.0,57.0,250.0,225.0,40.0,60.0,5.0,...,0.382,0.716,101.0,86.0,1.0,0.0,1.0,1.0,0.0,1983
414,7.0,CF,Ruppert Jones*,28.0,133.0,372.0,335.0,42.0,78.0,12.0,...,0.394,0.699,96.0,132.0,8.0,0.0,2.0,0.0,4.0,1983
415,8.0,RF,Sixto Lezcano,29.0,97.0,373.0,317.0,41.0,74.0,11.0,...,0.356,0.687,94.0,113.0,8.0,1.0,4.0,4.0,3.0,1983

## Historical Batting Data

In [74]:
# Loading CSV
historical_batting = "data/historical_batting_raw.csv"

# Reading CSV into a DF
batting_df = pd.read_csv(historical_batting, index_col = [0])
batting_df

,Name,S,C,F,Yrs,From,To,ASG,G,PA,...,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,Pos Summary
Rk,,,,,,,,,,,,,,,,,,,,,
1,Shawn Abner\abnersh01,S,-,-,5,1987,1991,0,254,569,...,4.0,4.0,27.0,100.0,0.207,0.249,0.303,0.552,54.0,O
2,Ed Acosta\acosted01,-,-,F,2,1971,1972,0,54,30,...,0.0,0.0,1.0,15.0,0.034,0.067,0.034,0.101,-69.0,1
3,Austin Adams\adamsau02,-,-,F,1,2020,2020,0,1,1,...,0.0,0.0,0.0,1.0,0.000,0.000,0.000,0.000,-100.0,-1
4,Mike Adams\adamsmi03,-,-,-,4,2008,2011,0,197,2,...,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,-100.0,1
5,Jon Adkins\adkinjo01,-,-,-,1,2006,2006,0,51,1,...,0.0,0.0,0.0,1.0,0.000,0.000,0.000,0.000,-100.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1046,Eric Yardley\yardler01,S,-,-,1,2019,2019,0,10,0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-1
1047,Kirby Yates\yateski01,-,-,F,4,2017,2020,1,174,2,...,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,-100.0,1
1048,Chris Young\youngch03,-,-,-,5,2006,2010,1,92,188,...,0.0,0.0,9.0,63.0,0.141,0.192,0.199,0.390,7.0,1
1049,Eric Young Sr.\younger01,-,-,-,2,2005,2006,0,112,310,...,15.0,8.0,31.0,28.0,0.241,0.320,0.348,0.668,81.0,O-4
1050,Lance Zawadzki\zawadla01,S,C,F,1,2010,2010,0,20,42,...,1.0,0.0,5.0,7.0,0.200,0.300,0.257,0.557,59.0,-15

In [75]:
batting_df['Name'] = batting_df['Name'].str.split('\\').str[0]
batting_df

,Name,S,C,F,Yrs,From,To,ASG,G,PA,...,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,Pos Summary
Rk,,,,,,,,,,,,,,,,,,,,,
1,Shawn Abner,S,-,-,5,1987,1991,0,254,569,...,4.0,4.0,27.0,100.0,0.207,0.249,0.303,0.552,54.0,O
2,Ed Acosta,-,-,F,2,1971,1972,0,54,30,...,0.0,0.0,1.0,15.0,0.034,0.067,0.034,0.101,-69.0,1
3,Austin Adams,-,-,F,1,2020,2020,0,1,1,...,0.0,0.0,0.0,1.0,0.000,0.000,0.000,0.000,-100.0,-1
4,Mike Adams,-,-,-,4,2008,2011,0,197,2,...,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,-100.0,1
5,Jon Adkins,-,-,-,1,2006,2006,0,51,1,...,0.0,0.0,0.0,1.0,0.000,0.000,0.000,0.000,-100.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1046,Eric Yardley,S,-,-,1,2019,2019,0,10,0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,-1
1047,Kirby Yates,-,-,F,4,2017,2020,1,174,2,...,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,-100.0,1
1048,Chris Young,-,-,-,5,2006,2010,1,92,188,...,0.0,0.0,9.0,63.0,0.141,0.192,0.199,0.390,7.0,1
1049,Eric Young Sr.,-,-,-,2,2005,2006,0,112,310,...,15.0,8.0,31.0,28.0,0.241,0.320,0.348,0.668,81.0,O-4
1050,Lance Zawadzki,S,C,F,1,2010,2010,0,20,42,...,1.0,0.0,5.0,7.0,0.200,0.300,0.257,0.557,59.0,-15

In [78]:
batting_df.to_csv('data/cleaned/historical_batting_data.csv', index=False)